---
- name: Set tex image
  hosts: tex
  vars:
    guest_user: "vagrant"
    common_path: "../../common"
    guest_home: "/home/{{ guest_user }}"
  become: true
  pre_tasks:
    - name: Include secret variables
      include_vars: "{{ common_path }}/secrets.yml"
    - name: Update repositories
      ansible.builtin.package: update_cache=yes
      changed_when: false
    - name: Include ssh key
      ansible.builtin.include_tasks: "{{ common_path }}/config_ssh_key.yml"
    - name: Create .config and .local folder
      ansible.builtin.include_tasks: "{{ common_path }}/create_home_folders.yml"
  tasks:
    - name: Install base packages
      ansible.builtin.include_tasks: "{{ common_path }}/install_base_packages.yml"
    - name: Install necessary tex packages
      ansible.builtin.package:
        name:
          - python3
          - python3-pip
          - perl
        update_cache: true
        state: present
    - name: Include wezterm install
      ansible.builtin.include_tasks: "{{ common_path }}/install_wezterm.yml"
    - name: Setup git global configs
      ansible.builtin.include_tasks: "{{ common_path }}/setup_git.yml"
    - name: Install nvim
      ansible.builtin.include_tasks: "{{ common_path }}/install_nvim.yml"
    - name: Setup nvim
      ansible.builtin.include_tasks: "{{ common_path }}/setup_nvim.yml"
    - name: Setup zsh
      ansible.builtin.include_tasks: "{{ common_path }}/setup_zsh.yml"
    - name: Install texlive
      ansible.builtin.include_tasks: "{{ common_path }}/install_texlive.yml"
...
