---
- name: Setup tex environment
  hosts: all
  vars:
    guest_user: "vagrant"
    github_user: "braulio-balanza"
  become: true
  pre_tasks:
    - name: Enable Flatpak
      ansible.builtin.package:
        name:
          - flatpak
        update_cache: true
    - name: Update repositories
      ansible.builtin.package: update_cache=yes
      # become_user: root
      changed_when: false
  tasks:
    - name: Install base packages
      ansible.builtin.package:
        name:
          - build-essential
          - nodejs
          - python3
          - python3-pip
          - git
          - bc
          - bat
        update_cache: true
        state: present
    - name: Install Wezterm
      ansible.builtin.get_url:
        url: https://github.com/wez/wezterm/releases/download/20221119-145034-49b9839f/WezTerm-20221119-145034-49b9839f-Ubuntu18.04.AppImage
        dest: /usr/bin/wezterm
        mode: '0755'
        force: true
    - name: Set locale to English so lualatex doesn't explode
      community.general.locale_gen:
        name: "en_US.UTF-8"
        state: present
    - name: Install texlive
      ansible.builtin.package:
        name: 
          - texlive-full
          - pandoc
        state: present
    - name: Setup git global configs
      include_tasks: setup_git.yml
    # - name: Include rust install tasks
      # include_tasks: install_rust.yml
    # - name: Include nvim install tasks
      # include_tasks: install_nvim.yml
...
