Vagrant.configure("2") do |config|
    config.vm.define :tex do |tex|
    tex.vm.box = "debian/bullseye64"
    tex.vm.box_url = "https://app.vagrantup.com/debian/boxes/bullseye64"
    tex.vm.box_version = "11.20221219.1"
    tex.vm.hostname = "tex"
    tex.ssh.username = "vagrant"
    tex.ssh.guest_port = 2298
    tex.ssh.port = 2298
    tex.vm.network "private_network", ip: "192.168.56.4"
    tex.vm.network "forwarded_port", guest: 22, host: 2298

    tex.vm.provider :virtualbox
    tex.vm.disk :disk, size: "20GB", primary: true
    config.vm.provider "virtualbox" do |v|
      v.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
      v.memory = 4096
      v.cpus = 2
    end

    tex.vm.synced_folder "workspace/", "/workspace/", create: true

    tex.vm.provision :ansible do |ansible|
    ansible.playbook = "provisioning/ansible.yml"
    ansible.raw_arguments = ["--vault-password-file=../secrets_password.txt"]
    end
  end
end
