---
# - name: Create wheel group
#   ansible.builtin.group:
#     name: wheel
#     state: present
# - name: Allow wheel to have passwordless sudoers
#   ansible.builtin.lineinfile:
#     dest: /etc/sudoers
#     state: present
#     regexp: '^%wheel'
#     line: '%wheel ALL=(ALL) NOPASSWD: ALL'
#     validate: 'visudo -cf %s'
- name: Create user
  ansible.builtin.user:
    name: vmnaut
    shell: /bin/bash
    groups: wheel
    append: true
    create_home: true
    generate_ssh_key: true
    ssh_key_type: ed25519
- name: Setup vagrant's ssh public key
  ansible.posix.authorized_key:
    user: vmnaut
    state: present
    manage_dir: true
    key: "{{ lookup('file', '../id_ed25519.pub') }}"
# - name: Setup ssh server
#   ansible.builtin.template:
#     src: sshd_config.j2
#     dest: /etc/ssh/sshd_config
#     owner: root
#     mode: '0600'
#     validate: /usr/sbin/sshd -t -f %s
#     backup: true
...
