---
- name: Install base dependencies
  hosts: openbsd
  become: true
  vars:
    guest_user: "vagrant"
    common_path: "../../common"
    guest_home: "/home/{{ guest_user }}"
  pre_tasks:
    - name: Include secret variables
      include_vars: "{{ common_path }}/secrets.yml"
    - name: Configure user and ssh configs
      ansible.builtin.include_tasks: "{{ common_path }}/config_ssh_key.yml"
  # - name: Update currently installed packages
  #   ansible.builtin.shell:
  #     cmd: |
  #       pkg_add -u
    - name: Create user folders
      ansible.builtin.include_tasks: "{{ common_path }}/create_home_folders.yml"
  tasks:
    - name: Install base packages
      ansible.builtin.package:
        name:
          - git
          - zsh
          - neovim
          - htop
          - neofetch
          - fd
          - ripgrep
          - exa
          - curl
          - fzf
          - bat
          - go
        state: latest
    - name: Setup git global configs
      ansible.builtin.include_tasks: "{{ common_path }}/setup_git.yml"
    - name: Setup neovim
      ansible.builtin.include_tasks: "{{ common_path }}/setup_nvim.yml"
    - name: Setup zsh
      ansible.builtin.include_tasks: "{{ common_path }}/setup_zsh.yml"
...
