Vagrant.configure("2") do |config|
    config.vm.define :nix_alma do |nix_alma|
    nix_alma.vm.box = "generic/alma9"
    nix_alma.vm.box_url = "https://app.vagrantup.com/generic/boxes/alma9"
    nix_alma.vm.hostname = "nix-alma"
    # nix_alma.ssh.username = "vmnaut"
    # nix_alma.ssh.private_key_path = "../id_ed25519"

    nix_alma.ssh.shell="bash"

    nix_alma.vm.network "private_network", ip: "192.168.56.4"
    config.vm.network "forwarded_port", guest: 8000, host: 8002

    nix_alma.vm.provider :virtualbox
    nix_alma.vm.disk :disk, size: "40960MB", primary: true
    config.vm.provider "virtualbox" do |v|
      v.memory = 16384
      v.cpus = 8
    end

    nix_alma.vm.synced_folder "workspace/", "/workspace/", create: true

    nix_alma.vm.provision "shell",
    inline: "wget -qO- https://nixos.org/nix/install | sh -s",
    privileged: false

    end
end
