Vagrant.configure("2") do |config|
    config.vm.define :debian do |debian|
    debian.vm.box = "debian/testing64"
    debian.vm.box_url = "https://app.vagrantup.com/debian/boxes/testing64"
    debian.vm.hostname = "debian"
    debian.ssh.guest_port = 2294
    debian.vm.network "forwarded_port", guest: 22, host: 2294
    # debian.ssh.username = "vmnaut"
    # debian.ssh.private_key_path = "../id_ed25519"

    debian.ssh.shell="bash"

    debian.vm.network "private_network", ip: "192.168.56.4"
    debian.vm.network "forwarded_port", guest: 8000, host: 8000

    debian.vm.provider :virtualbox
    debian.vm.disk :disk, size: "40960MB", primary: true
    config.vm.provider "virtualbox" do |v|
      v.memory = 16384
      v.cpus = 8
    end

    debian.vm.synced_folder "workspace/", "/workspace/", create: true

    debian.vm.provision :ansible do |ansible|
    ansible.playbook = "provisioning/ansible.yml"
    ansible.raw_arguments = ["--vault-password-file=../secrets_password.txt"]
    end
  end
end
