---
- name: Install base dependencies
  hosts: base
  become: true
  vars:
    guest_user: "vagrant"
  pre_tasks:
    - name: Enable Flatpak
      ansible.builtin.package:
        name:
          - flatpak
        update_cache: true
    - name: Update repositories
      ansible.builtin.package: update_cache=yes
      # become_user: root
      changed_when: false
    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  tasks:
    - name: Install base packages
      ansible.builtin.package:
        name:
          - build-essential
          - git
          - bc
          - bat
          - curl
          - neovim
        update_cache: true
        state: present
    - name: Include wezterm install
      include_tasks: install_wezterm.yml
    - name: Include rust install
      include_tasks: install_rust.yml
    - name: Setup git global configs
      include_tasks: setup_git.yml
...
