---
- name: Install base dependencies
  hosts: debian
  become: true
  vars:
    guest_user: "vagrant"
    common_path: "../../common"
    guest_home: "/home/{{ guest_user }}"
  pre_tasks:
    - name: Include secret variables
      ansible.builtin.include_vars: "{{ common_path }}/secrets.yml"
    - name: Configure user and ssh configs
      ansible.builtin.include_tasks: "{{ common_path }}/config_ssh_key.yml"
    - name: Enable Flatpak
      ansible.builtin.package:
        name:
          - flatpak
        update_cache: true
    - name: Update repositories
      ansible.builtin.package: update_cache=yes
      changed_when: false
    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    - name: Create .config folder
      ansible.builtin.include_tasks: "{{ common_path }}/create_conf.yml"
  tasks:
    - name: Install base packages
      ansible.builtin.include_tasks: "{{ common_path }}/install_base_packages.yml"
    - name: Include wezterm install
      ansible.builtin.include_tasks: "{{ common_path }}/install_wezterm.yml"
    - name: Setup git global configs
      ansible.builtin.include_tasks: "{{ common_path }}/setup_git.yml"
    - name: Install nvim
      ansible.builtin.include_tasks: "{{ common_path }}/install_nvim.yml"
    - name: Setup nvim
      ansible.builtin.include_tasks: "{{ common_path }}/setup_nvim.yml"
    - name: Setup zsh
      ansible.builtin.include_tasks: "{{ common_path }}/setup_zsh.yml"
    - name: Install rust
      ansible.builtin.include_tasks: "{{ common_path }}/install_rust.yml"
    - name: Install golang
      ansible.builtin.include_tasks: "{{ common_path }}/install_golang.yml"
    - name: Install nodejs
      ansible.builtin.package:
        name:
          - nodejs
          - npm
...
