---
- name: Install base dependencies
  hosts: base_debian
  become: true
  vars:
    guest_user: "vagrant"
    common_path: "../../common"
    guest_home: "/home/{{ guest_user }}"
  pre_tasks:
    - name: Include secret variables
      include_vars: "{{ common_path }}/secrets.yml"
    - name: Configure user and ssh configs
      ansible.builtin.include_tasks: "{{ common_path }}/config_ssh_key.yml"
    - name: Enable Flatpak
      ansible.builtin.package:
        name:
          - flatpak
        update_cache: true
    - name: Update repositories
      ansible.builtin.package: update_cache=yes
      changed_when: false
    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  tasks:
    - name: Install base packages
      ansible.builtin.package:
        name:
          - build-essential
          - git
          - bc
          - bat
          - curl
          - acl
          - fzf
          - ripgrep
          - exa
          - zsh
        update_cache: true
        state: present
    - name: Include wezterm install
      ansible.builtin.include_tasks: "{{ common_path }}/install_wezterm.yml"
    - name: Include rust install
      ansible.builtin.include_tasks: "{{ common_path }}/install_rust.yml"
    - name: Setup git global configs
      ansible.builtin.include_tasks: "{{ common_path }}/setup_git.yml"
    - name: Install nvim
      ansible.builtin.include_tasks: "{{ common_path }}/install_nvim.yml"
    - name: Install nodejs
      ansible.builtin.package:
        name:
          - nodejs
          - npm
    - name: Setup zsh
      ansible.builtin.include_tasks: "{{ common_path }}/setup_zsh.yml"
...
