---
- name: Install prerequisites
  ansible.builtin.package:
    name:
      - libgl1-mesa-glx
      - libegl1-mesa
      - libxrandr2
      - libxss1
      - libxcursor1
      - libxcomposite1
      - libasound2
      - libxi6
      - libxtst6
    state: present
- name: Download installer
  ansible.builtin.get_url:
    url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: /tmp/conda_install.sh
    mode: "0755"
    force: true
- name: Change shell to bash
  ansible.builtin.user:
    name: "{{ guest_user }}"
    shell: /bin/bash
  become: true
- name: Install Anaconda3
  ansible.builtin.shell:
    cmd: "/tmp/conda_install.sh -b -f"
...
