Vagrant.configure("2") do |config|
  config.vm.define :openbsd do |openbsd|

    config.vm.box = "generic/openbsd7"
    config.ssh.password = "vagrant"

    openbsd.vm.provider :virtualbox
    openbsd.vm.disk :disk, size: "40960MB", primary: true
    config.vm.provider "virtualbox" do |v|
      v.memory = 16384
      v.cpus = 6
    end
    openbsd.vm.hostname = "openbsd"

    openbsd.ssh.shell="sh"

    openbsd.vm.network "private_network", ip: "192.168.56.4"

    openbsd.vm.synced_folder "workspace/", "/workspace/", 
      create: true

    openbsd.vm.provision "shell",
      inline: "pkg_add -I python-3.10.9p0"


    openbsd.vm.provision :ansible do |ansible|
      ansible.playbook = "provisioning/ansible.yml"
      ansible.raw_arguments = ["--vault-password-file=../secrets_password.txt"]
    end
  end
end

