---
- name: Ensure wheel group exists
  ansible.builtin.group:
    name: wheel
    state: present
- name: Ensure wheel group has sudoer rights
  ansible.builtin.copy:
    content: '%wheel ALL=(ALL:ALL) NOPASSWD:ALL'
    dest: /etc/sudoers.d/wheel_no_password
    mode: 0440
    validate: '/usr/sbin/visudo -cf %s'
- name: Setup vagrant's ssh public key
  ansible.posix.authorized_key:
    user: vagrant
    state: present
    manage_dir: true
    key: "{{ lookup('file', '../id_ed25519.pub') }}"
...
