---
- name: Download Rust installer
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rust
- name: Install rust/cargo
  ansible.builtin.shell: /tmp/sh.rustup.rs -y && echo "[ -f ~/.cargo/env ] && source $HOME/.cargo/env" >> $HOME/.bashrc
  tags:
    - rust
  become_user: "{{ guest_user }}"
  become_method: "sudo"
...
