---
- name: Install nvim
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
    dest: /usr/bin/
    mode: a+x
- name: Update alternatives
  community.general.alternatives:
    name: nvim
    link: /usr/bin/nvim
    path: /usr/bin/nvim.appimage
...
