---
- name: Install nvim
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
    dest: /usr/bin/
    mode: a+x
- name: Update alternatives
  community.general.alternatives:
    name: nvim
    link: /usr/bin/nvim
    path: /usr/bin/nvim.appimage
- name: Create config dir if not exists
  ansible.builtin.file:
    path: "{{ guest_home }}/.config/nvim"
    state: directory
    mode: '0755'
- name: Clone configuration
  ansible.builtin.git:
    repo: "https://bbalanza:{{ github_token }}@github.com/bbalanza/nvim-dotfiles.git"
    dest: "{{ guest_home }}/.config/nvim"
...
