---
- name: Change user shell to zsh
  ansible.builtin.shell:
    cmd: |
      export SHELL_LOCATION=$( which zsh )
      chsh -s $SHELL_LOCATION {{ guest_user }}
- name: Clone dotfiles
  ansible.builtin.git:
    dest: "{{ guest_home }}/.config/zsh"
    repo: "https://bbalanza:{{ github_token}}@github.com/bbalanza/zsh_dotfiles.git"
  become_user: "{{ guest_user }}"
- name: Setup .zshenv
  ansible.builtin.blockinfile:
    dest: "{{ guest_home }}/.zshenv"
    block: |
      export EDITOR="nvim"
      export VISUAL="nvim"

      export ZDOTDIR="$HOME/.config/zsh"
      export HISTFILE="$ZDOTDIR/.zhistory"

      export HISTSIZE=10000
      export SAVEHIST=10000

      export XDG_CONFIG_HOME="$HOME/.config"
      export XDG_DATA_HOME="$XDG_CONFIG_HOME/local/share"
      export XDG_CACHE_HOME="$XDG_CONFIG_HOME/cache"
    create: true
  become_user: "{{ guest_user }}"
- name: Install oh-my-sh
  ansible.builtin.git:
    dest: "{{ guest_home }}/.oh-my-zsh"
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
  become_user: "{{ guest_user }}"
- name: Install fzf-tab
  ansible.builtin.git:
    repo: "https://github.com/Aloxaf/fzf-tab"
    dest: "{{ guest_home }}/.oh-my-zsh/custom/plugins/fzf-tab"
  become_user: "{{ guest_user }}"
- name: Install startship
  ansible.builtin.shell:
    executable: /usr/bin/zsh
    cmd: |
      curl -sS https://starship.rs/install.sh | sh -s -- --yes
  when: ansible_facts['hostname'] != 'openbsd'
- name: Add startshipconfig
  ansible.builtin.blockinfile:
    dest: "{{ guest_home }}/.config/starship.toml"
    create: true
    block: |
      format = '''
      $time$all
      '''

      [character]
      success_symbol = '[|-](bold green)'
      error_symbol = '[✖](bold red)'
      vimcmd_symbol = '[-|](bold green)'
      vimcmd_replace_one_symbol = '[-|](bold purple)'
      vimcmd_replace_symbol = '[-|](bold purple)'
      vimcmd_visual_symbol = '[-|](bold yellow)'

      [time]
      format = '|[$time]($style)| '
      disabled = false

      [line_break]
      disabled = false
  when: ansible_facts['hostname'] != 'openbsd'
- name: Setup minimal theme when using OpenBSD
  ansible.builtin.lineinfile:
    path: "{{ guest_home }}/.config/zsh/.zshrc"
    regexp: 'ZSH_THEME=".*"'
    line: 'ZSH_THEME="minimal"'
    owner: vagrant
    group: vagrant
    mode: '0755'
...
