Vagrant.configure("2") do |config|
    config.vm.define :base_freebsd do |base_freebsd|
    base_freebsd.vm.provider :virtualbox
    base_freebsd.vm.disk :disk, size: "40960MB", primary: true
    config.vm.provider "virtualbox" do |v|
      v.memory = 16384
      v.cpus = 6
    end

    config.vm.box = "freebsd/FreeBSD-13.2-RELEASE"
    base_freebsd.vm.box_version = "2023.04.07"
    base_freebsd.vm.box_url = "https://app.vagrantup.com/freebsd/boxes/FreeBSD-13.2-RELEASE"
    base_freebsd.vm.hostname = "freebsd"
    base_freebsd.ssh.shell="sh"
    base_freebsd.ssh.guest_port=2299

    base_freebsd.vm.network "private_network", ip: "192.168.56.4"
    base_freebsd.vm.network "forwarded_port", guest: 80, host: 8000
    base_freebsd.vm.network "forwarded_port", guest: 22, host: 2299

    base_freebsd.vm.synced_folder "workspace/", "/workspace/", 
      create: true, 
      type: "nfs",
      nfs_version: 4,
      mount_options: ['nocto,noatime']

    base_freebsd.vm.provision "shell" do |shell|
      ssh_pub_key = File.readlines("/home/kykeonaut/Dropbox/Dev/dev_envs/id_ed25519.pub").first.strip
      shell.inline = "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys"
      shell.inline = "pkg install -y python"
    end

    base_freebsd.vm.provision :ansible do |ansible|
    ansible.playbook = "provisioning/ansible.yml"
    ansible.raw_arguments = ["--vault-password-file=../secrets_password.txt"]
    end
  end
end
