---
- name: Install base dependencies
  hosts: base
  become: true
  vars:
    guest_user: "vagrant"
  pre_tasks:
    - name: Enable EPEL and Flatpak on RockyLinux
      ansible.builtin.package:
        name:
          - epel-release
          - flatpak
        update_cache: true
    - name: Update repositories
      ansible.builtin.package: update_cache=yes
      # become_user: root
      changed_when: false
    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  tasks:
    - name: Install base packages
      ansible.builtin.package:
        name:
          - build-essential
          - nodejs
          - python3-pip
          - git
          - bc
        update_cache: true
        state: present
    - name: Install Wezterm
      ansible.builtin.get_url:
        url: https://github.com/wez/wezterm/releases/download/20221119-145034-49b9839f/WezTerm-20221119-145034-49b9839f-Ubuntu18.04.AppImage
        dest: /usr/bin/wezterm
        mode: '0755'
        force: true
    # - name: Configure Wezterm
      # ansible.builtin.shell:
        # cmd: echo "alias wezterm='flatpak run org.wezfurlong.wezterm'" >> $HOME/.bashrc
      # become_user: '{{ guest_user }}'
    - name: Include rust install tasks
      include_tasks: install_rust.yml
    - name: Setup git global configs
      include_tasks: setup_git.yml
    - name: Install anaconda3
      include_tasks: install_anaconda3.yml
    # - name: Include nvim install tasks
      # include_tasks: install_nvim.yml
...
