Vagrant.configure("2") do |config|
    config.vm.define :base_debian do |base_debian|
    base_debian.vm.box = "debian/bullseye64"
    base_debian.vm.box_url = "https://app.vagrantup.com/debian/boxes/bullseye64"
    base_debian.vm.box_version = "11.20221219.1"
    base_debian.vm.hostname = "base-debian"
    base_debian.ssh.username = "vmnaut"
    base_debian.ssh.private_key_path = "id_ed25519"
    # base_debian.ssh.password = "vagrant"

    # base_debian.ssh.keys_only=false
    # base_debian.ssh.insert_key=false
    base_debian.ssh.shell="bash"

    base_debian.vm.network "private_network", ip: "192.168.56.4"

    base_debian.vm.provider :virtualbox
    base_debian.vm.disk :disk, size: "40960MB", primary: true
    config.vm.provider "virtualbox" do |v|
      v.memory = 16384
      v.cpus = 8
    end

    base_debian.vm.synced_folder "workspace/", "/workspace/", create: true

    base_debian.vm.provision :ansible do |ansible|
    ansible.playbook = "provisioning/ansible.yml"
    end
  end
end
